import Head from 'next/head'
import Contact from '../components/Contact'
import Features from '../components/Features'
import Header from '../components/Header'
import Hero from "../components/Hero"
import History from '../components/History'
import Staff from '../components/Staff'

export default function Home() {
  return (
    <>
      <Head>
        <title>Curly | Hair Salon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='overflow-hidden'>
        <Header />
        <Hero />
        <Features />
        <History />
        <Staff />
        <Contact />
      </main>
    </>
  )
}
