import Head from 'next/head'
import Features from '../components/Features'
import Hero from "../components/Hero"

export default function Home() {
  return (
    <>
      <Head>
        <title>Tainá Cabelereira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='overflow-hidden'>
        <Hero />
        <Features />
      </main>
    </>
  )
}
